Introduction
RodolfoFerro/gsbook pull request #1
Opened 2021-05-29 20:21 UTC by fanyCaz

Parte inicial del libro gs book.

2021-05-31 14:17 UTC, RodolfoFerro requested changes
¡Hola! Sorry que no había revisado mis notificaciones de GitHub, pero he revisado cuidadosamente el PR y he agregado algunos comentarios de redacción para actualizar antes de darle merge, ¿me cuentas si te laten?

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +At this moment in time, Artificial Intelligence doesn't have an exact description, even when is a field with a relative long history. The main problem when defining Artificial Intelligence is that it
- "(...) even when ***it*** is a field with a relative long history."
- "(...) we can think we have this ***characteristic*** (...)"

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +One person that kept it simple, was Alan Turing, who proposed : The Turing Test. This would allow us to decide if a computer is intelligent.
- "(...) who proposed The Turing Test." (Sin los dos puntos, me parece que en este caso no aplica.)

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +The test consist on having a human talk to an entity on another room, the entity can be other human or a machine. If the person making the test can not differenciate if is having a conversation with
- "The test ***consists in*** having a human ***talking**(...)"
- "If the person making the test can not ***differentiate*** if ***he/she*** is having (...)"
- "(...) we can conclude ***that*** the machine has artificial intelligence."

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +The machine that is intelligent must have the abilities to recognize the way a human talks, learn through time and be able to represent abstract concepts.But most importantly, it must be able to adap
- "(...) the way a human talks, ***to*** learn through time and ***to*** be able (...)"
- "(...) abstract concepts; but most importantly, it must (...)"

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +There are other scientist and engineers that claim true artificial intelligence is when a computer is rational. But this gives the idea of the computer being eficient, not human like. We, as humans (
- ***scientists***
- ***efficient***
- ***consciousness***
- "(...) this apradign ***focuses*** in (...)"

2021-05-31 14:17 UTC, RodolfoFerro commented on docs/introduction-to-ai.md
> +At the end, what ever algorithm we choose to implement artificial intelligence, we take human behaviour and try to emulate it.
- ***whatever***

2021-06-05 00:53 UTC, fanyCaz commented
Me han servido mucho tus comentarios.
También agregué 'Perspectiva histórica', y creo que sería todo por el PR.

2021-06-05 07:18 UTC, RodolfoFerro approved these changes

2021-06-05 07:19 UTC, RodolfoFerro commented
Quedó fenomenal, muchísimas gracias por la contribución. :')

Procedo a darle Merge al PR. :D

2021-06-05 07:19 UTC, merged

2021-06-05 07:23 UTC, RodolfoFerro commented
Por cierto, agregué un commit directo al `index.md` (https://github.com/RodolfoFerro/gsbook/commit/8c8439023f20f63ed4c37b937b4c0c58dd774f53), por si quieres hacer un git pull.